export const clothesitems = [
    {id: 1,
      img:'https://m.media-amazon.com/images/I/71vp8Lec9JL._AC_UL320_.jpg',
      title:'Scott International Men Regular Fit T-Shirt (Pack of 3) ',
      discountprice:'549',
      originalprice:'2397',
      discountrate:'77%',
    },
    {id: 2,
        img:'https://m.media-amazon.com/images/I/41YzZqnVSbL._AC_UL320_.jpg',
        title:'Smily Creation Womens Taffeta Silk Semi Stitched Anarkali Long Gown (Free Size) ',
        discountprice:'629',
        originalprice:'1599',
        discountrate:'61%',
      },
      {id: 3,
        img:'https://m.media-amazon.com/images/I/71qUv2Ya2PL._AC_UL320_.jpg',
        title:'Van Heusen Mens Drop Crotch Skinny Jeans ',
        discountprice:'999',
        originalprice:'1799',
        discountrate:'44%',
      },
      {id: 4,
        img:'https://m.media-amazon.com/images/I/61+BeHM80oL._AC_UL320_.jpg',
        title:'Broadstar Women Denim Blue Jeans ',
        discountprice:'749',
        originalprice:'1999',
        discountrate:'63%',
      },
      {id: 5,
        img:'https://m.media-amazon.com/images/I/71-XF3BbIfL._AC_UL320_.jpg',
        title:'MANQ Mens Slim Fit Suit ',
        discountprice:'3099',
        originalprice:' 6499',
        discountrate:'52%',
      },
      {id: 6,
        img:'https://m.media-amazon.com/images/I/61l00egujxL._AC_UL320_.jpg',
        title:'VASTRAMAY Mens Cotton & Silk Blend Regular Kurta ',
        discountprice:' 899',
        originalprice:'1599',
        discountrate:'44%',
      },
      {id: 7,
        img:'https://m.media-amazon.com/images/I/91GKFgnS5uL._AC_UL320_.jpg',
        title:'Yashika Womens Art Silk Saree With Blouse Piece(NAURTA_Free Size) ',
        discountprice:'279',
        originalprice:'1047',
        discountrate:'73%',
      },
      {id: 8,
        img:'https://m.media-amazon.com/images/I/71y7tZPdZML._AC_UL320_.jpg',
        title:'Miss Chase Womens Designer Wine Red Fringed Halter Neck Sleeveless Solid Maxi Front Slit Dress',
        discountprice:'719',
        originalprice:'1430.',
        discountrate:'67%',
      },


];